name: mysql_dart
description: Native MySQL client written in Dart. Tested with MySQL Percona Server (5.7, 8), MariaDB (10). Supports TLS.
version: 1.2.1
homepage: https://github.com/insinfo/mysql.dart
repository: https://github.com/insinfo/mysql.dart

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: '>=2.16.0 <4.0.0'

dependencies: 
  buffer: ^1.2.3
  crypto: ^3.0.5
  tuple: ^2.0.2

dev_dependencies:
  hex: ^0.2.0
  lints: ^4.0.0
  test: ^1.25.8
 